### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OLDIN** [Xfaider48/node-csgotm-api#1]
Hi, you have an error on the 759 line in the csgo_tm_api.js file
` if (!isNaN(page) && pade > 0) {`
[https://github.com/Xfaider48/node-csgotm-api/blob/master/csgo_tm_api.js/#LC759](url)

**Comment by Xfaider48** [comment]
Hi! Thank you. I fixed it in [0.1.5](https://github.com/Xfaider48/node-csgotm-api/commit/4765f37e09dd80ba66ec6dc5dd532825b04c9717)
