### ISSUE TITLE
sellCreateTradeRequest 

### ISSUE THREAD

**Issue by malsatin** [Xfaider48/node-csgotm-api#10]
Может вместо такого костыля сделать Object.values(types).some(t => t === type)?

**Comment by Xfaider48** [comment]
@MattRh  Что то костыль, что твой вариант костыль) меж двух костылей мне больше симпатизирует мой из за меньшего кол-ва действий.

**Comment by malsatin** [comment]
Ну мой вариант не пропускает всякие In/Out/ouT и т.д. Не знаю, как маркет относится к таким вариациям, если норм, то можем зарывать тред

**Comment by Xfaider48** [comment]
@MattRh с этим ты прав, поэтому я немного [доработал](https://github.com/Xfaider48/node-csgotm-api/commit/9e9433aea36291b9967403cbf56ddee81ad91af0#diff-ee22a0612de97e1ad5f184ed5cdb19e4R866) свой вариант
