### ISSUE TITLE
Script example/Пример скрипта

### ISSUE THREAD

**Issue by 4ikistik** [Xfaider48/node-csgotm-api#8]
I can see a working script that can transfer and accept purchased items on the site?
Я могу увидеть рабочий скрипт, который может передавать и принимать купленные предметы на сайте?

**Comment by Xfaider48** [comment]
@4ikistik Нет. Данный пакет помогает работать с API. Больше ничего. С его помощью можно "попросить" маркет создать трейд для передачи вещей от Вас или к Вам. Однако, чтобы принять трейд - нужен стим, и в этом Вам может помочь [этот](https://www.npmjs.com/package/steam-tradeoffer-manager) и [этот](https://www.npmjs.com/package/steamcommunity) пакеты.

**Comment by 4ikistik** [comment]
а как реализовать с помощью Вашего пакета (вопрос Steam trade offers не стоит, там есть примеры)
> "попросить" маркет создать трейд для передачи вещей от Вас или к Вам

**Comment by Xfaider48** [comment]
@4ikistik Из [документации](https://market.csgo.com/docs/) маркета видно, что нужен метод ItemRequest - запросить трейд на отправку/получение.
Из за того, что данный пакет почти ничего не умеет, документации минимум и касается она основых моментов.
На будущее: открываем [исходный код](https://github.com/Xfaider48/node-csgotm-api/blob/master/src/csgo_tm_api.js), ищем нужный нам метод ItemRequest, видим что необходимо вызвать метод пакета [sellCreateTradeRequest](https://github.com/Xfaider48/node-csgotm-api/blob/master/src/csgo_tm_api.js#L777)

**Comment by 4ikistik** [comment]
Я сам использую https://github.com/millworm/Csgo.tm-Bot и хотел перейти на js и мне надо только реагировать на покупку и продажу на сайте. Вы сами не используете этот модуль или вы, как фрилансер помогаете в реализации функции данного модуля?

**Comment by Xfaider48** [comment]
@4ikistik Использую. Когда понадобился функционал - начал писать модуль. В конечном счету решил его выложить, чтобы никому больше не пришлось лишнюю работу выполнять.

А реализовывать тут больше нечего. Это не бот. Все методы маркета уже реализованы (исключением являются сокеты)

**Comment by malsatin** [comment]
@Xfaider48 Ох уж эти сокеты.. Я не знаю стоит их добавить сюда или стоит вынести в отдельный пакет. И стоит ли вообще выкладывать на гитхаб, т.к. там без костылей никак

**Comment by Xfaider48** [comment]
@MattRh Не уверен что сокеты нужны. Действительно, там костыли и реализация лишь в совокупности с API вызовами. Раз уж пакет "API" - пусть таковым и остается :)
